<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Rest_API_Project"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.086">
    <properties></properties>

            <testcase
                name="soft_Assert"
                time="0.086"
                classname="org.RestAPi.ex_06_Assertions.Lab26_TestNg_SoftAssertion">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Dinesh] but found [dinesh]">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Dinesh] but found [dinesh]
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)org.RestAPi.ex_06_Assertions.Lab26_TestNg_SoftAssertion.soft_Assert(Lab26_TestNg_SoftAssertion.java:15)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)java.base/java.lang.reflect.Method.invoke(Method.java:565)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1604)org.testng.TestRunner.privateRun(TestRunner.java:741)org.testng.TestRunner.run(TestRunner.java:616)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


</testsuite>
